apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-configmap
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
    {{- range $key, $val := .Values.configs }}
    {{ $key }}: {{ $val }}
    {{- end }}
